vich_uploader:
    db_driver: orm
    mappings:
        profile_pictures:
            uri_prefix: /uploads/profile_pictures
            upload_destination: '%kernel.project_dir%/public/uploads/profile_pictures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
